-- db/montar.sql — MONTAR UMA VIAGEM INTEIRA EM SQL.
--
-- ARQUIVO GERADO por scripts/gerar-montar-sql.mjs (npm run sql:build).
-- Nao edite a mao: lib/montar.test.ts compara este arquivo com o que o gerador
-- produz a partir de lib/schema.ts, e a proxima geracao apagaria a edicao.
--
-- O QUE ISTO E
--
-- Um jeito de escrever a viagem inteira — roteiro, voos, cruzeiro, hospedagem,
-- cidades, checklist, documentos, documentacao exigida, contatos e dinheiro — em
-- comandos SQL, e receber no fim o MESMO arquivo JSON que a tela ja importa.
-- Nao ha formato novo e nao ha segunda gravadora de viagem: o que sai daqui entra
-- pelo botao Importar (aba Participantes e dados) ou por `npm run montar`, e quem
-- grava continua sendo lib/importar.ts, com a validacao e a autorizacao de sempre.
--
-- COMO SE USA
--
--   1. select montar.viagem('europa-2027', 'Europa 2027', '2027-01-02', '2027-01-20');
--   2. select montar.participante('europa-2027', p_nome => 'Ana');
--      select montar.roteiro('europa-2027', p_ocorre_em => '2027-01-02T09:00',
--                            p_titulo => 'Chegada em Lisboa', p_cidade => 'Lisboa');
--      ... uma chamada por item, em qualquer ordem;
--   3. select * from montar.conferir('europa-2027');   -- o que esta errado ANTES
--   4. select montar.arquivo('europa-2027');           -- o JSON pronto
--
-- Chamar `montar.viagem` de novo com o mesmo nome RECOMECA o rascunho: rodar o
-- mesmo .sql duas vezes tem que produzir uma viagem, nao duas.
--
-- O rascunho e uma tabela comum (`montar.itens`). Corrigir um item ja escrito e
-- um `update ... set dado = dado || jsonb_build_object(...)`, e tirar um e um
-- `delete`. Nao ha funcao para isso porque nao precisa haver.
--
-- ONDE ELE NAO CHEGA
--
--   - Nao escreve nas tabelas do app. Este schema so monta jsonb; nenhuma funcao
--     aqui alcanca `trips`, `travelers` ou `expenses`. Uma gravadora em PL/pgSQL
--     seria uma segunda copia das regras de autorizacao — a que fica para tras.
--   - Importar sempre CRIA viagem nova. Para completar uma viagem que ja existe,
--     edite pela tela ou monte o arquivo, importe, e mova o que interessa.
--   - Id de linha nao vira argumento: o arquivo liga tudo por NOME
--     (`assigned_to_nomes`, `dono_nome`, `reserva`, `categoria`, `pagador`),
--     porque a importacao cria a viagem do zero e os ids antigos nao existem la.
--   - Bytes de documento nao passam por aqui, como nao passam pelo export: o
--     arquivo guarda a ficha do documento, e o PDF sobe pela tela do cofre.
--
-- SEGURANCA: quem roda isto tem a DATABASE_URL, ou seja, ja esta acima de
-- qualquer papel do app — o recorte por papel protege a REDE, nao o console do
-- banco. Por isso nada aqui LE tabela do app: um `select` que juntasse
-- `travelers` a um rascunho publicaria passaporte alheio para dentro de um jsonb
-- que depois vira arquivo e circula por e-mail. Para tirar dados de uma viagem
-- que ja existe, use GET /api/export, que corta por papel.

create schema if not exists montar;

-- O rascunho: a viagem (bloco unico) e os itens de cada secao.
--
-- Duas tabelas, e nao um jsonb so, porque `insert` e `delete` de UM item tem que
-- ser triviais — a metade do tempo de montar uma viagem e corrigir um horario. A
-- ordem de `id` e a ordem em que o item entra no arquivo.
create table if not exists montar.rascunhos (
  id            text primary key default gen_random_uuid()::text,
  nome          text not null unique,
  viagem        jsonb not null,
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists montar.itens (
  id          bigint generated by default as identity primary key,
  rascunho_id text not null references montar.rascunhos(id) on delete cascade,
  secao       text not null,
  dado        jsonb not null
);

create index if not exists idx_montar_itens on montar.itens (rascunho_id, secao, id);

-- ---------------------------------------------------------------- apoio

-- Resolve o nome do rascunho. Erra alto: um nome errado devolvendo null faria o
-- item entrar em lugar nenhum e o script terminar "com sucesso" sem o passeio.
create or replace function montar.__rascunho(p_rascunho text) returns text
language plpgsql stable as $fn$
declare v_id text;
begin
  select id into v_id from montar.rascunhos where nome = p_rascunho;
  if v_id is null then
    raise exception 'rascunho "%" nao existe. Comece por montar.viagem(...).', p_rascunho;
  end if;
  return v_id;
end $fn$;

-- Os itens de uma secao, na ordem em que entraram.
create or replace function montar.__secao(p_id text, p_secao text) returns jsonb
language sql stable as $fn$
  select coalesce(jsonb_agg(dado order by id), '[]'::jsonb)
    from montar.itens where rascunho_id = p_id and secao = p_secao
$fn$;

-- ---------------------------------------------------------------- secoes

-- Abre (ou REABRE) um rascunho. Chamar de novo apaga os itens do rascunho de
-- mesmo nome: um script .sql precisa poder rodar duas vezes sem duplicar o
-- roteiro inteiro, e "recomecar" e o unico significado seguro de rodar de novo.
create or replace function montar.viagem(
  p_rascunho               text,
  p_nome                   text,
  p_data_partida           date,
  p_data_retorno           date,
  p_subtitulo              text default null,
  p_descricao              text default null,
  p_moeda                  text default null,
  p_fuso                   text default null,
  p_cor_destaque           text default null,
  p_capa_url               text default null,
  p_arquivada              boolean default null,
  p_orcamento_centavos     integer default null
) returns text
language plpgsql as $fn$
declare v_id text;
begin
  insert into montar.rascunhos (nome, viagem)
  values (p_rascunho, jsonb_strip_nulls(jsonb_build_object(
    'nome', to_jsonb(p_nome),
    'data_partida', to_char(p_data_partida, 'YYYY-MM-DD'),
    'data_retorno', to_char(p_data_retorno, 'YYYY-MM-DD'),
    'subtitulo', to_jsonb(p_subtitulo),
    'descricao', to_jsonb(p_descricao),
    'moeda', to_jsonb(p_moeda),
    'fuso', to_jsonb(p_fuso),
    'cor_destaque', to_jsonb(p_cor_destaque),
    'capa_url', to_jsonb(p_capa_url),
    'arquivada', to_jsonb(p_arquivada),
    'orcamento_centavos', to_jsonb(p_orcamento_centavos)
  )))
  on conflict (nome) do update
     set viagem = excluded.viagem, atualizado_em = now()
  returning id into v_id;
  delete from montar.itens where rascunho_id = v_id;
  return p_rascunho;
end $fn$;

-- Acrescenta um item a secao "participantes" do rascunho.
create or replace function montar.participante(
  p_rascunho               text,
  p_nome                   text,
  p_email                  text default null,
  p_papel                  text default null,
  p_telefone               text default null,
  p_passaporte             text default null,
  p_documento              text default null,
  p_nascimento             date default null,
  p_ordem                  integer default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_papel is not null and p_papel <> all (array['proprietario', 'editor', 'visualizador']) then
    raise exception 'participantes.papel: % nao esta na lista (proprietario, editor, visualizador)', p_papel;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'participantes', jsonb_strip_nulls(jsonb_build_object(
    'nome', to_jsonb(p_nome),
    'email', to_jsonb(p_email),
    'papel', to_jsonb(p_papel),
    'telefone', to_jsonb(p_telefone),
    'passaporte', to_jsonb(p_passaporte),
    'documento', to_jsonb(p_documento),
    'nascimento', to_char(p_nascimento, 'YYYY-MM-DD'),
    'ordem', to_jsonb(p_ordem)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "roteiro" do rascunho.
create or replace function montar.roteiro(
  p_rascunho               text,
  p_ocorre_em              timestamp,
  p_titulo                 text,
  p_fim_em                 timestamp default null,
  p_cidade                 text default null,
  p_local                  text default null,
  p_endereco               text default null,
  p_lat                    double precision default null,
  p_lon                    double precision default null,
  p_descricao              text default null,
  p_tipo                   text default null,
  p_ancora                 boolean default null,
  p_distancia_m            integer default null,
  p_duracao_min            integer default null,
  p_transporte             text default null,
  p_como_chegar            text default null,
  p_dicas                  text default null,
  p_links                  text default null,
  p_custo_centavos         integer default null,
  p_reserva                text default null,
  p_documento              text default null,
  p_nota                   text default null,
  p_ordem                  integer default null,
  p_opcoes                 jsonb default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_tipo is not null and p_tipo <> all (array['voo', 'trem', 'onibus', 'traslado', 'caminhada', 'cruzeiro', 'hospedagem', 'local', 'passeio', 'ponto', 'restaurante', 'refeicao', 'compras', 'evento', 'tarefa', 'compromisso', 'dica', 'observacao', 'documento']) then
    raise exception 'roteiro.tipo: % nao esta na lista (voo, trem, onibus, traslado, caminhada, cruzeiro, hospedagem, local, passeio, ponto, restaurante, refeicao, compras, evento, tarefa, compromisso, dica, observacao, documento)', p_tipo;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'roteiro', jsonb_strip_nulls(jsonb_build_object(
    'ocorre_em', to_char(p_ocorre_em, 'YYYY-MM-DD"T"HH24:MI'),
    'titulo', to_jsonb(p_titulo),
    'fim_em', to_char(p_fim_em, 'YYYY-MM-DD"T"HH24:MI'),
    'cidade', to_jsonb(p_cidade),
    'local', to_jsonb(p_local),
    'endereco', to_jsonb(p_endereco),
    'lat', to_jsonb(p_lat),
    'lon', to_jsonb(p_lon),
    'descricao', to_jsonb(p_descricao),
    'tipo', to_jsonb(p_tipo),
    'ancora', to_jsonb(p_ancora),
    'distancia_m', to_jsonb(p_distancia_m),
    'duracao_min', to_jsonb(p_duracao_min),
    'transporte', to_jsonb(p_transporte),
    'como_chegar', to_jsonb(p_como_chegar),
    'dicas', to_jsonb(p_dicas),
    'links', to_jsonb(p_links),
    'custo_centavos', to_jsonb(p_custo_centavos),
    'reserva', to_jsonb(p_reserva),
    'documento', to_jsonb(p_documento),
    'nota', to_jsonb(p_nota),
    'ordem', to_jsonb(p_ordem),
    'opcoes', to_jsonb(p_opcoes)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "dias" do rascunho.
create or replace function montar.dia(
  p_rascunho               text,
  p_dia                    date,
  p_titulo                 text default null,
  p_cidade                 text default null,
  p_pais                   text default null,
  p_resumo                 text default null,
  p_ancora                 boolean default null,
  p_alertas                text default null,
  p_antes_sair             text default null,
  p_antes_dormir           text default null,
  p_links                  text default null,
  p_mapa_url               text default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'dias', jsonb_strip_nulls(jsonb_build_object(
    'dia', to_char(p_dia, 'YYYY-MM-DD'),
    'titulo', to_jsonb(p_titulo),
    'cidade', to_jsonb(p_cidade),
    'pais', to_jsonb(p_pais),
    'resumo', to_jsonb(p_resumo),
    'ancora', to_jsonb(p_ancora),
    'alertas', to_jsonb(p_alertas),
    'antes_sair', to_jsonb(p_antes_sair),
    'antes_dormir', to_jsonb(p_antes_dormir),
    'links', to_jsonb(p_links),
    'mapa_url', to_jsonb(p_mapa_url)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "voos" do rascunho.
create or replace function montar.voo(
  p_rascunho               text,
  p_companhia              text,
  p_numero                 text default null,
  p_origem_iata            text default null,
  p_origem_cidade          text default null,
  p_destino_iata           text default null,
  p_destino_cidade         text default null,
  p_parte_em               timestamp default null,
  p_chega_em               timestamp default null,
  p_duracao_min            integer default null,
  p_localizador            text default null,
  p_terminal               text default null,
  p_portao                 text default null,
  p_assento                text default null,
  p_bagagem                text default null,
  p_nota                   text default null,
  p_ordem                  integer default null,
  p_escalas                jsonb default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'voos', jsonb_strip_nulls(jsonb_build_object(
    'companhia', to_jsonb(p_companhia),
    'numero', to_jsonb(p_numero),
    'origem_iata', to_jsonb(p_origem_iata),
    'origem_cidade', to_jsonb(p_origem_cidade),
    'destino_iata', to_jsonb(p_destino_iata),
    'destino_cidade', to_jsonb(p_destino_cidade),
    'parte_em', to_char(p_parte_em, 'YYYY-MM-DD"T"HH24:MI'),
    'chega_em', to_char(p_chega_em, 'YYYY-MM-DD"T"HH24:MI'),
    'duracao_min', to_jsonb(p_duracao_min),
    'localizador', to_jsonb(p_localizador),
    'terminal', to_jsonb(p_terminal),
    'portao', to_jsonb(p_portao),
    'assento', to_jsonb(p_assento),
    'bagagem', to_jsonb(p_bagagem),
    'nota', to_jsonb(p_nota),
    'ordem', to_jsonb(p_ordem),
    'escalas', to_jsonb(p_escalas)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "cruzeiros" do rascunho.
create or replace function montar.cruzeiro(
  p_rascunho               text,
  p_navio                  text,
  p_companhia              text default null,
  p_embarque_em            timestamp default null,
  p_desembarque_em         timestamp default null,
  p_porto_embarque         text default null,
  p_porto_desembarque      text default null,
  p_cabine                 text default null,
  p_localizador            text default null,
  p_terminal               text default null,
  p_nota                   text default null,
  p_portos                 jsonb default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'cruzeiros', jsonb_strip_nulls(jsonb_build_object(
    'navio', to_jsonb(p_navio),
    'companhia', to_jsonb(p_companhia),
    'embarque_em', to_char(p_embarque_em, 'YYYY-MM-DD"T"HH24:MI'),
    'desembarque_em', to_char(p_desembarque_em, 'YYYY-MM-DD"T"HH24:MI'),
    'porto_embarque', to_jsonb(p_porto_embarque),
    'porto_desembarque', to_jsonb(p_porto_desembarque),
    'cabine', to_jsonb(p_cabine),
    'localizador', to_jsonb(p_localizador),
    'terminal', to_jsonb(p_terminal),
    'nota', to_jsonb(p_nota),
    'portos', to_jsonb(p_portos)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "reservas" do rascunho.
create or replace function montar.reserva(
  p_rascunho               text,
  p_nome                   text,
  p_tipo                   text default null,
  p_cidade                 text default null,
  p_inicio_em              timestamp default null,
  p_fim_em                 timestamp default null,
  p_endereco               text default null,
  p_link                   text default null,
  p_telefone               text default null,
  p_localizador            text default null,
  p_valor_centavos         integer default null,
  p_nota                   text default null,
  p_ordem                  integer default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_tipo is not null and p_tipo <> all (array['hospedagem', 'restaurante', 'passeio', 'ingresso', 'carro', 'transporte', 'outro']) then
    raise exception 'reservas.tipo: % nao esta na lista (hospedagem, restaurante, passeio, ingresso, carro, transporte, outro)', p_tipo;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'reservas', jsonb_strip_nulls(jsonb_build_object(
    'nome', to_jsonb(p_nome),
    'tipo', to_jsonb(p_tipo),
    'cidade', to_jsonb(p_cidade),
    'inicio_em', to_char(p_inicio_em, 'YYYY-MM-DD"T"HH24:MI'),
    'fim_em', to_char(p_fim_em, 'YYYY-MM-DD"T"HH24:MI'),
    'endereco', to_jsonb(p_endereco),
    'link', to_jsonb(p_link),
    'telefone', to_jsonb(p_telefone),
    'localizador', to_jsonb(p_localizador),
    'valor_centavos', to_jsonb(p_valor_centavos),
    'nota', to_jsonb(p_nota),
    'ordem', to_jsonb(p_ordem)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "lugares" do rascunho.
create or replace function montar.lugar(
  p_rascunho               text,
  p_cidade                 text,
  p_pais                   text default null,
  p_dias                   integer default null,
  p_status                 text default null,
  p_chega_em               date default null,
  p_sai_em                 date default null,
  p_notas                  text default null,
  p_lat                    double precision default null,
  p_lon                    double precision default null,
  p_ordem                  integer default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_status is not null and p_status <> all (array['planejada', 'visitada']) then
    raise exception 'lugares.status: % nao esta na lista (planejada, visitada)', p_status;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'lugares', jsonb_strip_nulls(jsonb_build_object(
    'cidade', to_jsonb(p_cidade),
    'pais', to_jsonb(p_pais),
    'dias', to_jsonb(p_dias),
    'status', to_jsonb(p_status),
    'chega_em', to_char(p_chega_em, 'YYYY-MM-DD'),
    'sai_em', to_char(p_sai_em, 'YYYY-MM-DD'),
    'notas', to_jsonb(p_notas),
    'lat', to_jsonb(p_lat),
    'lon', to_jsonb(p_lon),
    'ordem', to_jsonb(p_ordem)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "checklist" do rascunho.
create or replace function montar.checklist(
  p_rascunho               text,
  p_titulo                 text,
  p_categoria              text default null,
  p_escopo                 text default null,
  p_prazo_ideal            date default null,
  p_prazo_maximo           date default null,
  p_valor_estimado_centavos integer default null,
  p_detalhe                text default null,
  p_ordem                  integer default null,
  p_assigned_to_nomes      text[] default null,
  p_prioridade             text default null,
  p_pais                   text default null,
  p_cidade                 text default null,
  p_pendente               boolean default null,
  p_fonte_tipo             text default null,
  p_fonte_detalhe          text default null,
  p_fonte_consultado_em    date default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_escopo is not null and p_escopo <> all (array['global', 'pessoal']) then
    raise exception 'checklist.escopo: % nao esta na lista (global, pessoal)', p_escopo;
  end if;
  if p_prioridade is not null and p_prioridade <> all (array['obrigatorio', 'importante', 'recomendado', 'opcional']) then
    raise exception 'checklist.prioridade: % nao esta na lista (obrigatorio, importante, recomendado, opcional)', p_prioridade;
  end if;
  if p_fonte_tipo is not null and p_fonte_tipo <> all (array['documento', 'pesquisa', 'sugestao', 'manual']) then
    raise exception 'checklist.fonte_tipo: % nao esta na lista (documento, pesquisa, sugestao, manual)', p_fonte_tipo;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'checklist', jsonb_strip_nulls(jsonb_build_object(
    'titulo', to_jsonb(p_titulo),
    'categoria', to_jsonb(p_categoria),
    'escopo', to_jsonb(p_escopo),
    'prazo_ideal', to_char(p_prazo_ideal, 'YYYY-MM-DD'),
    'prazo_maximo', to_char(p_prazo_maximo, 'YYYY-MM-DD'),
    'valor_estimado_centavos', to_jsonb(p_valor_estimado_centavos),
    'detalhe', to_jsonb(p_detalhe),
    'ordem', to_jsonb(p_ordem),
    'assigned_to_nomes', to_jsonb(p_assigned_to_nomes),
    'prioridade', to_jsonb(p_prioridade),
    'pais', to_jsonb(p_pais),
    'cidade', to_jsonb(p_cidade),
    'pendente', to_jsonb(p_pendente),
    'fonte_tipo', to_jsonb(p_fonte_tipo),
    'fonte_detalhe', to_jsonb(p_fonte_detalhe),
    'fonte_consultado_em', to_char(p_fonte_consultado_em, 'YYYY-MM-DD')
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "documentos" do rascunho.
create or replace function montar.documento(
  p_rascunho               text,
  p_titulo                 text,
  p_valor                  text default null,
  p_tipo                   text default null,
  p_categoria              text default null,
  p_arquivo_url            text default null,
  p_arquivo_nome           text default null,
  p_arquivo_mime           text default null,
  p_arquivo_bytes          integer default null,
  p_obs                    text default null,
  p_ordem                  integer default null,
  p_escopo                 text default null,
  p_tags                   text[] default null,
  p_importante             boolean default null,
  p_offline                boolean default null,
  p_validade               date default null,
  p_pais                   text default null,
  p_cidade                 text default null,
  p_dia                    date default null,
  p_dono_nome              text default null,
  p_assigned_to_nomes      text[] default null,
  p_reserva                text default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_tipo is not null and p_tipo <> all (array['texto', 'link', 'telefone', 'arquivo']) then
    raise exception 'documentos.tipo: % nao esta na lista (texto, link, telefone, arquivo)', p_tipo;
  end if;
  if p_categoria is not null and p_categoria <> all (array['pessoal', 'passaporte', 'seguro', 'voo', 'trem', 'onibus', 'hospedagem', 'reserva', 'ingresso', 'transfer', 'financeiro', 'saude', 'emergencia', 'outro']) then
    raise exception 'documentos.categoria: % nao esta na lista (pessoal, passaporte, seguro, voo, trem, onibus, hospedagem, reserva, ingresso, transfer, financeiro, saude, emergencia, outro)', p_categoria;
  end if;
  if p_escopo is not null and p_escopo <> all (array['global', 'pessoal']) then
    raise exception 'documentos.escopo: % nao esta na lista (global, pessoal)', p_escopo;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'documentos', jsonb_strip_nulls(jsonb_build_object(
    'titulo', to_jsonb(p_titulo),
    'valor', to_jsonb(p_valor),
    'tipo', to_jsonb(p_tipo),
    'categoria', to_jsonb(p_categoria),
    'arquivo_url', to_jsonb(p_arquivo_url),
    'arquivo_nome', to_jsonb(p_arquivo_nome),
    'arquivo_mime', to_jsonb(p_arquivo_mime),
    'arquivo_bytes', to_jsonb(p_arquivo_bytes),
    'obs', to_jsonb(p_obs),
    'ordem', to_jsonb(p_ordem),
    'escopo', to_jsonb(p_escopo),
    'tags', to_jsonb(p_tags),
    'importante', to_jsonb(p_importante),
    'offline', to_jsonb(p_offline),
    'validade', to_char(p_validade, 'YYYY-MM-DD'),
    'pais', to_jsonb(p_pais),
    'cidade', to_jsonb(p_cidade),
    'dia', to_char(p_dia, 'YYYY-MM-DD'),
    'dono_nome', to_jsonb(p_dono_nome),
    'assigned_to_nomes', to_jsonb(p_assigned_to_nomes),
    'reserva', to_jsonb(p_reserva)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "requisitos" do rascunho.
create or replace function montar.requisito(
  p_rascunho               text,
  p_nome                   text,
  p_descricao              text default null,
  p_categoria              text default null,
  p_obrigatorio            boolean default null,
  p_aplica_todos           boolean default null,
  p_exige_numero           boolean default null,
  p_exige_validade         boolean default null,
  p_exige_arquivo          boolean default null,
  p_campo_perfil           text default null,
  p_prazo                  date default null,
  p_obs                    text default null,
  p_ordem                  integer default null,
  p_assigned_to_nomes      text[] default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_categoria is not null and p_categoria <> all (array['pessoal', 'passaporte', 'seguro', 'voo', 'trem', 'onibus', 'hospedagem', 'reserva', 'ingresso', 'transfer', 'financeiro', 'saude', 'emergencia', 'outro']) then
    raise exception 'requisitos.categoria: % nao esta na lista (pessoal, passaporte, seguro, voo, trem, onibus, hospedagem, reserva, ingresso, transfer, financeiro, saude, emergencia, outro)', p_categoria;
  end if;
  if p_campo_perfil is not null and p_campo_perfil <> all (array['cpf', 'rg', 'passaporte', 'nascimento', 'nacionalidade', 'emergencia']) then
    raise exception 'requisitos.campo_perfil: % nao esta na lista (cpf, rg, passaporte, nascimento, nacionalidade, emergencia)', p_campo_perfil;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'requisitos', jsonb_strip_nulls(jsonb_build_object(
    'nome', to_jsonb(p_nome),
    'descricao', to_jsonb(p_descricao),
    'categoria', to_jsonb(p_categoria),
    'obrigatorio', to_jsonb(p_obrigatorio),
    'aplica_todos', to_jsonb(p_aplica_todos),
    'exige_numero', to_jsonb(p_exige_numero),
    'exige_validade', to_jsonb(p_exige_validade),
    'exige_arquivo', to_jsonb(p_exige_arquivo),
    'campo_perfil', to_jsonb(p_campo_perfil),
    'prazo', to_char(p_prazo, 'YYYY-MM-DD'),
    'obs', to_jsonb(p_obs),
    'ordem', to_jsonb(p_ordem),
    'assigned_to_nomes', to_jsonb(p_assigned_to_nomes)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "entregas" do rascunho.
create or replace function montar.entrega(
  p_rascunho               text,
  p_numero                 text default null,
  p_validade               date default null,
  p_emitido_em             date default null,
  p_status                 text default null,
  p_comentario             text default null,
  p_requisito_nome         text default null,
  p_dono_nome              text default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_status is not null and p_status <> all (array['pendente', 'enviado', 'aprovado', 'rejeitado', 'correcao']) then
    raise exception 'entregas.status: % nao esta na lista (pendente, enviado, aprovado, rejeitado, correcao)', p_status;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'entregas', jsonb_strip_nulls(jsonb_build_object(
    'numero', to_jsonb(p_numero),
    'validade', to_char(p_validade, 'YYYY-MM-DD'),
    'emitido_em', to_char(p_emitido_em, 'YYYY-MM-DD'),
    'status', to_jsonb(p_status),
    'comentario', to_jsonb(p_comentario),
    'requisito_nome', to_jsonb(p_requisito_nome),
    'dono_nome', to_jsonb(p_dono_nome)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "emergencia" do rascunho.
create or replace function montar.emergencia(
  p_rascunho               text,
  p_titulo                 text,
  p_telefone               text default null,
  p_detalhe                text default null,
  p_ordem                  integer default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'emergencia', jsonb_strip_nulls(jsonb_build_object(
    'titulo', to_jsonb(p_titulo),
    'telefone', to_jsonb(p_telefone),
    'detalhe', to_jsonb(p_detalhe),
    'ordem', to_jsonb(p_ordem)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "categorias" do rascunho.
create or replace function montar.categoria(
  p_rascunho               text,
  p_nome                   text,
  p_ordem                  integer default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'categorias', jsonb_strip_nulls(jsonb_build_object(
    'nome', to_jsonb(p_nome),
    'ordem', to_jsonb(p_ordem)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "custos" do rascunho.
create or replace function montar.custo(
  p_rascunho               text,
  p_descricao              text,
  p_valor_centavos         integer,
  p_categoria              text default null,
  p_moeda                  text default null,
  p_ocorre_em              date default null,
  p_pagador                text default null,
  p_divisao                text default null,
  p_estimado               boolean default null,
  p_nota                   text default null,
  p_ordem                  integer default null,
  p_divisoes               jsonb default null,
  p_parcelas               jsonb default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  if p_divisao is not null and p_divisao <> all (array['igual', 'peso', 'personalizado']) then
    raise exception 'custos.divisao: % nao esta na lista (igual, peso, personalizado)', p_divisao;
  end if;
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'custos', jsonb_strip_nulls(jsonb_build_object(
    'descricao', to_jsonb(p_descricao),
    'valor_centavos', to_jsonb(p_valor_centavos),
    'categoria', to_jsonb(p_categoria),
    'moeda', to_jsonb(p_moeda),
    'ocorre_em', to_char(p_ocorre_em, 'YYYY-MM-DD'),
    'pagador', to_jsonb(p_pagador),
    'divisao', to_jsonb(p_divisao),
    'estimado', to_jsonb(p_estimado),
    'nota', to_jsonb(p_nota),
    'ordem', to_jsonb(p_ordem),
    'divisoes', to_jsonb(p_divisoes),
    'parcelas', to_jsonb(p_parcelas)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- Acrescenta um item a secao "pagamentos" do rascunho.
create or replace function montar.pagamento(
  p_rascunho               text,
  p_valor_centavos         integer,
  p_de                     text default null,
  p_para                   text default null,
  p_ocorre_em              date default null,
  p_despesa                text default null,
  p_parcela                integer default null,
  p_referencia             text default null,
  p_nota                   text default null
) returns bigint
language plpgsql as $fn$
declare v_id bigint;
begin
  insert into montar.itens (rascunho_id, secao, dado)
  values (montar.__rascunho(p_rascunho), 'pagamentos', jsonb_strip_nulls(jsonb_build_object(
    'valor_centavos', to_jsonb(p_valor_centavos),
    'de', to_jsonb(p_de),
    'para', to_jsonb(p_para),
    'ocorre_em', to_char(p_ocorre_em, 'YYYY-MM-DD'),
    'despesa', to_jsonb(p_despesa),
    'parcela', to_jsonb(p_parcela),
    'referencia', to_jsonb(p_referencia),
    'nota', to_jsonb(p_nota)
  )))
  returning id into v_id;
  return v_id;
end $fn$;

-- ---------------------------------------------------------------- saida

-- O arquivo de importacao, pronto para o botao Importar.
--
-- `schemaVersion` sai de lib/schema.ts na geracao: um numero digitado aqui viraria
-- a unica versao que nao acompanha o app.
create or replace function montar.arquivo(p_rascunho text) returns jsonb
language sql stable as $fn$
  select jsonb_build_object(
    'schemaVersion', 3,
    'viagem', r.viagem,
    'participantes', montar.__secao(r.id, 'participantes'),
    'roteiro', montar.__secao(r.id, 'roteiro'),
    'dias', montar.__secao(r.id, 'dias'),
    'voos', montar.__secao(r.id, 'voos'),
    'cruzeiros', montar.__secao(r.id, 'cruzeiros'),
    'reservas', montar.__secao(r.id, 'reservas'),
    'lugares', montar.__secao(r.id, 'lugares'),
    'checklist', montar.__secao(r.id, 'checklist'),
    'documentos', montar.__secao(r.id, 'documentos'),
    'requisitos', montar.__secao(r.id, 'requisitos'),
    'entregas', montar.__secao(r.id, 'entregas'),
    'emergencia', montar.__secao(r.id, 'emergencia'),
    'categorias', montar.__secao(r.id, 'categorias'),
    'custos', montar.__secao(r.id, 'custos'),
    'pagamentos', montar.__secao(r.id, 'pagamentos')
  )
  from montar.rascunhos r
  where r.nome = p_rascunho
$fn$;

-- Le um arquivo exportado de volta para um rascunho, para editar em SQL e reemitir.
-- E o caminho de volta do round-trip: GET /api/export -> montar.carregar -> editar
-- -> montar.arquivo -> Importar.
create or replace function montar.carregar(p_rascunho text, p_arquivo jsonb) returns text
language plpgsql as $fn$
declare v_id text;
begin
  insert into montar.rascunhos (nome, viagem)
  values (p_rascunho, p_arquivo -> 'viagem')
  on conflict (nome) do update set viagem = excluded.viagem, atualizado_em = now()
  returning id into v_id;
  delete from montar.itens where rascunho_id = v_id;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'participantes', x from jsonb_array_elements(coalesce(p_arquivo -> 'participantes', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'roteiro', x from jsonb_array_elements(coalesce(p_arquivo -> 'roteiro', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'dias', x from jsonb_array_elements(coalesce(p_arquivo -> 'dias', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'voos', x from jsonb_array_elements(coalesce(p_arquivo -> 'voos', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'cruzeiros', x from jsonb_array_elements(coalesce(p_arquivo -> 'cruzeiros', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'reservas', x from jsonb_array_elements(coalesce(p_arquivo -> 'reservas', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'lugares', x from jsonb_array_elements(coalesce(p_arquivo -> 'lugares', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'checklist', x from jsonb_array_elements(coalesce(p_arquivo -> 'checklist', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'documentos', x from jsonb_array_elements(coalesce(p_arquivo -> 'documentos', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'requisitos', x from jsonb_array_elements(coalesce(p_arquivo -> 'requisitos', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'entregas', x from jsonb_array_elements(coalesce(p_arquivo -> 'entregas', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'emergencia', x from jsonb_array_elements(coalesce(p_arquivo -> 'emergencia', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'categorias', x from jsonb_array_elements(coalesce(p_arquivo -> 'categorias', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'custos', x from jsonb_array_elements(coalesce(p_arquivo -> 'custos', '[]'::jsonb)) x;
  insert into montar.itens (rascunho_id, secao, dado)
  select v_id, 'pagamentos', x from jsonb_array_elements(coalesce(p_arquivo -> 'pagamentos', '[]'::jsonb)) x;
  return p_rascunho;
end $fn$;

-- Apaga um rascunho inteiro. Os itens vao junto pelo `on delete cascade`.
create or replace function montar.apagar(p_rascunho text) returns void
language sql as $fn$
  delete from montar.rascunhos where nome = p_rascunho
$fn$;

-- O que existe no rascunho, em uma linha por secao. Primeira coisa a olhar.
create or replace function montar.resumo(p_rascunho text)
returns table(secao text, itens bigint)
language sql stable as $fn$
  select i.secao, count(*)
    from montar.itens i
    join montar.rascunhos r on r.id = i.rascunho_id
   where r.nome = p_rascunho
   group by i.secao
   order by i.secao
$fn$;

-- ---------------------------------------------------------------- conferencia

-- O que esta errado no rascunho, ANTES de gerar o arquivo.
--
-- Nao repete o zod: `TripImportSchema` ja recusa data inexistente, centavos
-- fracionado e enum fora da lista, e `npm run montar` valida contra ele. O que
-- mora aqui e o que o zod NAO tem como ver — uma secao olhando para a outra.
-- Cada linha destas ja custou uma importacao que passou verde e entregou viagem
-- errada: pagador que ninguem reconhece entra como despesa sem pagador, documento
-- pessoal sem dono e rebaixado para global (fica visivel para a viagem inteira),
-- e entrega orfa e descartada em SILENCIO por lib/importar.ts.
--
-- 'erro' = a importacao vai perder ou torcer esse dado.
-- 'aviso' = entra, mas provavelmente nao e o que voce quis dizer.
create or replace function montar.conferir(p_rascunho text)
returns table(gravidade text, secao text, item text, problema text)
language plpgsql stable as $fn$
declare
  v_id     text := montar.__rascunho(p_rascunho);
  v_viagem jsonb;
begin
  select r.viagem into v_viagem from montar.rascunhos r where r.id = v_id;

  return query
  -- a viagem em si
  select 'erro', 'viagem', coalesce(v_viagem ->> 'nome', '?'),
         'data_retorno e anterior a data_partida'
   where (v_viagem ->> 'data_retorno')::date < (v_viagem ->> 'data_partida')::date

  union all
  select 'aviso', 'participantes', '-', 'a viagem nao tem nenhum participante'
   where not exists (
     -- Alias obrigatorio: secao tambem e uma coluna de SAIDA desta funcao, e sem
     -- o prefixo x. o Postgres recusa a consulta inteira por ambiguidade.
     select 1 from montar.itens x where x.rascunho_id = v_id and x.secao = 'participantes'
   )

  -- nome repetido quebra TODA ligacao por nome deste arquivo
  union all
  select 'erro', 'participantes', d.nome,
         'nome repetido: as ligacoes por nome (pagador, dono_nome, assigned_to_nomes) ficam ambiguas'
    from (
      select i.dado ->> 'nome' as nome, count(*) as n
        from montar.itens i
       where i.rascunho_id = v_id and i.secao = 'participantes'
       group by 1 having count(*) > 1
    ) d

  -- documento pessoal sem dono: a importacao rebaixa para global, e o passaporte
  -- de uma pessoa fica visivel para a viagem inteira.
  union all
  select 'erro', 'documentos', coalesce(i.dado ->> 'titulo', '?'),
         'escopo pessoal sem dono_nome: a importacao rebaixa para global e o documento fica visivel para todos'
    from montar.itens i
   where i.rascunho_id = v_id and i.secao = 'documentos'
     and i.dado ->> 'escopo' = 'pessoal'
     and coalesce(i.dado ->> 'dono_nome', '') = ''

  -- divisao personalizada que nao fecha com o total
  union all
  select 'erro', 'custos', coalesce(i.dado ->> 'descricao', '?'),
         'divisao personalizada soma ' || s.soma || ' e a despesa e ' || (i.dado ->> 'valor_centavos')
    from montar.itens i
    cross join lateral (
      select coalesce(sum((x ->> 'valor_centavos')::bigint), 0) as soma
        from jsonb_array_elements(coalesce(i.dado -> 'divisoes', '[]'::jsonb)) x
    ) s
   where i.rascunho_id = v_id and i.secao = 'custos'
     and i.dado ->> 'divisao' = 'personalizado'
     and jsonb_array_length(coalesce(i.dado -> 'divisoes', '[]'::jsonb)) > 0
     and s.soma <> (i.dado ->> 'valor_centavos')::bigint

  -- parcelas que nao somam a despesa
  union all
  select 'erro', 'custos', coalesce(i.dado ->> 'descricao', '?'),
         'as parcelas somam ' || s.soma || ' e a despesa e ' || (i.dado ->> 'valor_centavos')
    from montar.itens i
    cross join lateral (
      select coalesce(sum((x ->> 'valor_centavos')::bigint), 0) as soma
        from jsonb_array_elements(coalesce(i.dado -> 'parcelas', '[]'::jsonb)) x
    ) s
   where i.rascunho_id = v_id and i.secao = 'custos'
     and jsonb_array_length(coalesce(i.dado -> 'parcelas', '[]'::jsonb)) > 0
     and s.soma <> (i.dado ->> 'valor_centavos')::bigint

  -- prazo maximo antes do ideal
  union all
  select 'aviso', 'checklist', coalesce(i.dado ->> 'titulo', '?'),
         'prazo_maximo e anterior a prazo_ideal'
    from montar.itens i
   where i.rascunho_id = v_id and i.secao = 'checklist'
     and (i.dado ->> 'prazo_maximo')::date < (i.dado ->> 'prazo_ideal')::date

  -- requisito restrito a ninguem: a importacao o abre para todo mundo
  union all
  select 'aviso', 'requisitos', coalesce(i.dado ->> 'nome', '?'),
         'aplica_todos = false sem assigned_to_nomes: a importacao volta a exigir de todos'
    from montar.itens i
   where i.rascunho_id = v_id and i.secao = 'requisitos'
     and (i.dado ->> 'aplica_todos') = 'false'
     and jsonb_array_length(coalesce(i.dado -> 'assigned_to_nomes', '[]'::jsonb)) = 0

  union all
  select 'aviso', 'roteiro',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'dia', '?'),
         'ocorre_em (' || (i.dado ->> 'ocorre_em') || ') cai fora da viagem'
    from montar.itens i
   where i.rascunho_id = v_id and i.secao = 'roteiro'
     and left(i.dado ->> 'ocorre_em', 10)::date
         not between (v_viagem ->> 'data_partida')::date and (v_viagem ->> 'data_retorno')::date
  union all
  select 'aviso', 'dias',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'dia', '?'),
         'dia (' || (i.dado ->> 'dia') || ') cai fora da viagem'
    from montar.itens i
   where i.rascunho_id = v_id and i.secao = 'dias'
     and left(i.dado ->> 'dia', 10)::date
         not between (v_viagem ->> 'data_partida')::date and (v_viagem ->> 'data_retorno')::date
  union all
  select 'aviso', 'voos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'dia', '?'),
         'parte_em (' || (i.dado ->> 'parte_em') || ') cai fora da viagem'
    from montar.itens i
   where i.rascunho_id = v_id and i.secao = 'voos'
     and left(i.dado ->> 'parte_em', 10)::date
         not between (v_viagem ->> 'data_partida')::date and (v_viagem ->> 'data_retorno')::date
  union all
  select 'aviso', 'reservas',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'dia', '?'),
         'inicio_em (' || (i.dado ->> 'inicio_em') || ') cai fora da viagem'
    from montar.itens i
   where i.rascunho_id = v_id and i.secao = 'reservas'
     and left(i.dado ->> 'inicio_em', 10)::date
         not between (v_viagem ->> 'data_partida')::date and (v_viagem ->> 'data_retorno')::date
  union all
  select 'aviso', 'cruzeiros',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'dia', '?'),
         'embarque_em (' || (i.dado ->> 'embarque_em') || ') cai fora da viagem'
    from montar.itens i
   where i.rascunho_id = v_id and i.secao = 'cruzeiros'
     and left(i.dado ->> 'embarque_em', 10)::date
         not between (v_viagem ->> 'data_partida')::date and (v_viagem ->> 'data_retorno')::date

  union all
  select 'aviso', 'roteiro',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'reserva cita ' || quote_literal(v.valor) || ', que nao existe em reservas.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'reserva' as valor) v
   where i.rascunho_id = v_id and i.secao = 'roteiro' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'reservas'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'aviso', 'roteiro',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'documento cita ' || quote_literal(v.valor) || ', que nao existe em documentos.titulo'
    from montar.itens i
    cross join lateral (select i.dado ->> 'documento' as valor) v
   where i.rascunho_id = v_id and i.secao = 'roteiro' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'documentos'
          and a.dado ->> 'titulo' = v.valor
     )
  union all
  select 'erro', 'checklist',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'assigned_to_nomes cita ' || quote_literal(v.valor) || ', que nao existe em participantes.nome'
    from montar.itens i
    cross join lateral (select jsonb_array_elements_text(coalesce(i.dado -> 'assigned_to_nomes', '[]'::jsonb)) as valor) v
   where i.rascunho_id = v_id and i.secao = 'checklist' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'participantes'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'erro', 'documentos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'dono_nome cita ' || quote_literal(v.valor) || ', que nao existe em participantes.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'dono_nome' as valor) v
   where i.rascunho_id = v_id and i.secao = 'documentos' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'participantes'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'erro', 'documentos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'assigned_to_nomes cita ' || quote_literal(v.valor) || ', que nao existe em participantes.nome'
    from montar.itens i
    cross join lateral (select jsonb_array_elements_text(coalesce(i.dado -> 'assigned_to_nomes', '[]'::jsonb)) as valor) v
   where i.rascunho_id = v_id and i.secao = 'documentos' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'participantes'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'aviso', 'documentos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'reserva cita ' || quote_literal(v.valor) || ', que nao existe em reservas.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'reserva' as valor) v
   where i.rascunho_id = v_id and i.secao = 'documentos' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'reservas'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'erro', 'requisitos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'assigned_to_nomes cita ' || quote_literal(v.valor) || ', que nao existe em participantes.nome'
    from montar.itens i
    cross join lateral (select jsonb_array_elements_text(coalesce(i.dado -> 'assigned_to_nomes', '[]'::jsonb)) as valor) v
   where i.rascunho_id = v_id and i.secao = 'requisitos' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'participantes'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'erro', 'entregas',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'requisito_nome cita ' || quote_literal(v.valor) || ', que nao existe em requisitos.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'requisito_nome' as valor) v
   where i.rascunho_id = v_id and i.secao = 'entregas' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'requisitos'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'erro', 'entregas',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'dono_nome cita ' || quote_literal(v.valor) || ', que nao existe em participantes.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'dono_nome' as valor) v
   where i.rascunho_id = v_id and i.secao = 'entregas' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'participantes'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'erro', 'custos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'pagador cita ' || quote_literal(v.valor) || ', que nao existe em participantes.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'pagador' as valor) v
   where i.rascunho_id = v_id and i.secao = 'custos' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'participantes'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'aviso', 'custos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'categoria cita ' || quote_literal(v.valor) || ', que nao existe em categorias.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'categoria' as valor) v
   where i.rascunho_id = v_id and i.secao = 'custos' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'categorias'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'erro', 'pagamentos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'de cita ' || quote_literal(v.valor) || ', que nao existe em participantes.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'de' as valor) v
   where i.rascunho_id = v_id and i.secao = 'pagamentos' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'participantes'
          and a.dado ->> 'nome' = v.valor
     )
  union all
  select 'erro', 'pagamentos',
         coalesce(i.dado ->> 'titulo', i.dado ->> 'nome', i.dado ->> 'descricao', '?'),
         'para cita ' || quote_literal(v.valor) || ', que nao existe em participantes.nome'
    from montar.itens i
    cross join lateral (select i.dado ->> 'para' as valor) v
   where i.rascunho_id = v_id and i.secao = 'pagamentos' and v.valor is not null
     and not exists (
       select 1 from montar.itens a
        where a.rascunho_id = v_id and a.secao = 'participantes'
          and a.dado ->> 'nome' = v.valor
     )
  ;
end $fn$;
